# Generated by Django 6.0.4 on 2026-05-05 12:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('APARTMENT', 'Appartement'), ('HOUSE', 'Maison'), ('COMMERCIAL', 'Local commercial'), ('LAND', 'Terrain')], max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(default='France', max_length=100)),
                ('surface_area', models.FloatField(help_text='Surface en m²')),
                ('rooms', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('RENTED', 'Loué'), ('MAINTENANCE', 'En maintenance')], default='AVAILABLE', max_length=20)),
                ('blockchain_contract_address', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING', 'En attente signature'), ('ACTIVE', 'Actif'), ('COMPLETED', 'Terminé'), ('TERMINATED', 'Résilié'), ('DISPUTED', 'En litige')], default='DRAFT', max_length=20)),
                ('blockchain_contract_address', models.CharField(blank=True, max_length=200, null=True)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=200, null=True)),
                ('contract_pdf', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_contracts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
